[package]
name = "meikipop-gui"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fontdb = "0.23"
meikipop-native = { path = "../native" }
slint = { version = "=1.17.0", default-features = false, features = [
    "backend-winit-x11",
    "compat-1-2",
    "image-default-formats",
    "renderer-software",
    "std",
    "system-tray",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
slint-build = "=1.17.0"
