export { OcrPopup, FormattedEntry } from "popup.slint";

export component MeikiPopTray inherits SystemTrayIcon {
    icon: @image-url("../../../resources/icon.ico");
    title: "MeikiPop";
    tooltip: "MeikiPop";

    callback quit();
    callback choose-screen();

    Menu {
        MenuItem {
            title: "Choose screen";
            activated => { choose-screen(); }
        }
        MenuSeparator { }
        MenuItem {
            title: "Quit";
            activated => { quit(); }
        }
    }
}
