export { SettingsWindow }from "settings.slint";
export { OcrPopup, FormattedEntry }from "popup.slint";

export struct OcrProviderOption {
    id: string,
    name: string,
}

export component MeikiPopTray inherits SystemTrayIcon {
    in-out property <bool> is-paused: false;
    in-out property <string> selected-provider: "meikiocr";
    in-out property <string> selected-scan-mode: "auto";

    in property <[OcrProviderOption]> providers;

    callback show-settings();
    callback quit();
    callback choose-screen();
    callback choose-provider(string);
    callback choose-scan-mode(string);

    tooltip: "Meikipop";
    icon: root.is-paused
        ? @image-url("../../../resources/icon.inactive.ico")
        : @image-url("../../../resources/icon.ico");

    Menu {
        MenuItem {
            title: "Settings";
            activated => { root.show-settings(); }
        }

        MenuItem {
            title: "Choose screen";
            activated => { root.choose-screen(); }
        }

        Menu {
            title: "Choose provider";

            for provider in providers: MenuItem {
                title: provider.name;
                checkable: true;
                checked: provider.id == selected-provider;
                activated => { choose-provider(provider.id); }
            }
        }

        MenuSeparator { }

        Menu {
            title: "Scan Mode";
            MenuItem {
                title: "Auto";
                checkable: true;
                checked: root.selected-scan-mode == "auto";
                activated => { root.choose-scan-mode("auto"); }
            }
            MenuItem {
                title: "Hold Hotkey";
                checkable: true;
                checked: root.selected-scan-mode == "hotkey";
                activated => { root.choose-scan-mode("hotkey"); }
            }
        }

        MenuSeparator { }

        MenuItem {
            title: "Pause meikipop";
            checkable: true;
            checked <=> root.is-paused;
        }

        MenuSeparator { }

        MenuItem {
            title: "Quit";
            activated => { root.quit(); }
        }
    }
}
