export { OcrPopup } from "popup.slint";

export component MeikiPopTray inherits SystemTrayIcon {
    icon: @image-url("../../src/meikipop/resources/icon.ico");
    title: "MeikiPop";
    tooltip: "MeikiPop";

    callback quit();
    callback show-popup();

    Menu {
        MenuItem {
            title: "Show OCR popup";
            activated => { show-popup(); }
        }
        MenuItem {
            title: "Quit";
            activated => { quit(); }
        }
    }
}
