[package]
name = "meikipop-gui"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fontdb = "0.23"
meikipop-native = { path = "../../crates/native" }
slint = { version = "=1.17.0", default-features = false, features = [
    "compat-1-2",
    "image-default-formats",
    "std",
    "system-tray",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(target_os = "linux")'.dependencies]
slint = { version = "=1.17.0", default-features = false, features = [
    "backend-winit-x11",
    "renderer-skia",
] }

[target.'cfg(target_os = "macos")'.dependencies]
slint = { version = "=1.17.0", default-features = false, features = [
    "backend-winit",
    "renderer-femtovg-wgpu",
] }

[build-dependencies]
slint-build = "=1.17.0"
